sonar.projectKey=DevOps-Lab-API
sonar.projectName=DevOps Lab API
sonar.sources=.
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**
sonar.test.inclusions=tests/**/*.js
sonar.sourceEncoding=UTF-8
